#FROM python:3.11-slim
FROM registry.access.redhat.com/ubi9/python-311

WORKDIR /app

RUN pip install --no-cache-dir poetry

COPY pyproject.toml poetry.lock ./
COPY requirements.txt ./

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-root

ENV HTTP_PROXY=http://10.210.195.1:8080
ENV HTTPS_PROXY=http://10.210.195.1:8080

# RUN dnf intall -y python3 python3-pip
RUN python3 -m pip install --upgrade pip
RUN pip3 install poetry
RUN python -m pip install --upgrade pip
RUN pip install poetry==2.2.1
RUN pip install -r requirements.txt

RUN export PATH="$HOME/.local/bin:$PATH"

# Install dependencies
RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction --no-ansi --no-root

# Copy app code
COPY . .

EXPOSE 8000

# CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]